get book's cover image
maria-antoniak/goodreads-scraper pull request #35
Opened 2022-07-30 20:02 UTC by abarkansalim

2022-09-27 17:57 UTC, maria-antoniak commented
Looks great, thank you! A couple thoughts:

1. I don't think we should include this by default (since not everyone will want this images taking up space). Maybe we can add an optional argument to include this.
2. The Goodreads website has changed a lot recently; does this still work?

2022-11-05 13:14 UTC, clach04 requested changes

2022-11-05 13:14 UTC, clach04 commented on get_books.py
> +            'cover_image':          get_cover_image(soup),
Recommend this be renamed, append `_uri` for consistency (see line 172) and clarity.

2022-11-07 15:19 UTC, maria-antoniak approved these changes
Looks good, thank you!

2022-11-08 00:48 UTC, clach04 approved these changes
👍 I've not tested/ran this but lgtm :-)

2022-12-27 17:48 UTC, merged